import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#182849] h-screen">
        <div className="max-w-[1000px] mx-auto px-4 space-y-6">
          <header data-theme="night" className="rounded-b-xl ">
            <Navbar />
          </header>
          <main>{children}</main>
          <Footer data-theme="night" />
        </div>
      </body>
    </html>
  );
}
